[versions]
pluginyml = "0.6.0"
runtask = "2.3.0"
shadow = "8.1.7"

minecraft = "1.20.6"
paperapi = "1.20.6-R0.1-SNAPSHOT"

cloudcore = "1.1.0-SNAPSHOT"
configurate = "4.1.2"
bstats = "3.0.2"

discord4j = "3.3.0-SNAPSHOT"
spark-api = "0.1-SNAPSHOT"

[plugins]
pluginyml-paper = { id = "net.minecrell.plugin-yml.paper", version.ref = "pluginyml" }
runtask-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paperapi" }

configurate-gson = { module = "org.spongepowered:configurate-gson", version.ref = "configurate" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

cloudcore = { module = "dev.booky:cloudcore", version.ref = "cloudcore" }
discord4j-core = { module = "com.discord4j:discord4j-core", version.ref = "discord4j" }
spark-api = { module = "me.lucko:spark-api", version.ref = "spark-api" }
